name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Restart backend with PM2
        run: |
          cd backend
          pm2 restart mhss-api || pm2 start index.js --name mhss-api