name: Deploy to EC2 (self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # labels 
    runs-on: [self-hosted, ec2, mhss]

    steps:
      - name: Check runner is alive
        run: |
          whoami
          hostname
          node -v || true
          npm -v  || true
          pm2 -v  || true

      - name: Checkout repository
        uses: actions/checkout@v4

      # --- BACKEND ---
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Restart API with PM2
        working-directory: backend
        run: |
          # Start or restart the API (no error if not running)
          pm2 restart mhss-api || pm2 start server.js --name mhss-api
          pm2 save

      # --- FRONTEND ---
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        env:
          # Your frontend expects API at /api in production
          # (we already proxy /api via Nginx, so nothing else needed)
          CI: "false"
        run: npm run build

      - name: Publish build to Nginx root
        run: |
          sudo mkdir -p /var/www/mhss/app/frontend
          sudo rm -rf /var/www/mhss/app/frontend/build
          sudo cp -r frontend/build /var/www/mhss/app/frontend/build
          sudo chown -R ubuntu:ubuntu /var/www/mhss/app

      - name: Reload Nginx
        run: sudo systemctl reload nginx