name: Deploy to EC2 (ubuntu-runner)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_PATH: ${{ secrets.EC2_PATH }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          source: "."
          target: ${{ env.EC2_PATH }}

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ env.EC2_KEY }}
          script: |
            cd ${{ env.EC2_PATH }}
            pm2 stop all || true
            cd backend && npm install
            pm2 start server.js --name mhss-api --update-env
            cd ../frontend && npm install && npm run build
            pm2 serve build 3000 --name mhss-frontend --spa
            pm2 save